### ISSUE TITLE
Analysis pipeline: steps forward

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/Rt-without-renewal#195]
This is a meta-issue enumerating the tasks to be done to get to robust/repeatable analysis, as discussed in #193 .

## Task list

- [ ] Create a `DrWatson` project for the pipeline. This requires a bit of thought about what features we want.
- [ ] Within the project setup an appropriate environment, including loading `EpiAware`
- [ ] Design generation of "truth" data script as described in `README`, along with saving data.
- [ ] Define the full sequence of different scenario options, e.g. as [here](https://juliadynamics.github.io/DrWatson.jl/dev/workflow/#3.-Prepare-simulations).
- [ ] Construct and test a function for going from scenario specification to running inference. At this point defining the output to save is important.
- [ ] Blend `Dagger.jl` checkpointing into the scenario inference loop process, e.g. like [here](https://juliaparallel.org/Dagger.jl/dev/checkpointing/).
- [ ] Evaluation method on inference output. I'm assuming we outsource this to `scoringutils`.

**Comment by seabbs** [comment]
Agree. The thing I want to steer clear of here if possible is being able to do this only in some limited subset of cases vs all cases.

**Comment by SamuelBrand1** [comment]
> Agree. The thing I want to steer clear of here if possible is being able to do this only in some limited subset of cases vs all cases.

This should work for any model built on inferring an underlying white noise process.

**Comment by SamuelBrand1** [comment]
> > Agree. The thing I want to steer clear of here if possible is being able to do this only in some limited subset of cases vs all cases.
> 
> This should work for any model built on inferring an underlying white noise process.

This has turned out to be the hard limit of the approach too as per https://github.com/TuringLang/Turing.jl/issues/2239
